### ISSUE TITLE
run on 138k

### ISSUE THREAD

**Issue by 2575ahxu** [sususjysjy/Linux-on-c906-with-litex#1]
![image](https://github.com/user-attachments/assets/34c60c99-e51b-453f-b743-10f97047b74d)
Could you please tell me how to solve this problem mentioned in this picture?

**Comment by kevinsu20** [comment]
> ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA3NDgsIm5iZiI6MTcyOTUwMDQ0OCwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODdiOTQxNTNhNjRkYTUxMmIwNDExNGY1ODQ0YzVjYjE5ZTFlMzc0OTM1N2Q0N2E3ODQ5NGFhOTZhMDVkNDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gt8HZhBQWODUNVXjs3D5yByrf0yOST7Vdgq9GDq3Iic) Could you please tell me how to solve this problem mentioned in this picture?

Sorry, it's been too long. Which repo is this issue from?

**Comment by Jurisu25** [comment]
> ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?

Sorry, it's been too long. Which repo is this issue from?

**Comment by Stars-Collector** [comment]
> > ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?
> 
> Sorry, it's been too long. Which repo is this issue from?

It's from https://github.com/enjoy-digital/litex/issues/1793 ,and I also meet this problem.There seems to be a problem with DDR,and I can't find any solutions from litex documents.

**Comment by Jurisu25** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?
> > 
> > 
> > Sorry, it's been too long. Which repo is this issue from?
> 
> It's from [enjoy-digital/litex#1793](https://github.com/enjoy-digital/litex/issues/1793) ,and I also meet this problem.There seems to be a problem with DDR,and I can't find any solutions from litex documents.

Are you two in a team? Am I right to guess that it's for participating in a domestic competition? 138k with Litex isn't very practical; I suggest using SDRAM

**Comment by Stars-Collector** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?
> > > 
> > > 
> > > Sorry, it's been too long. Which repo is this issue from?
> > 
> > 
> > It's from [enjoy-digital/litex#1793](https://github.com/enjoy-digital/litex/issues/1793) ,and I also meet this problem.There seems to be a problem with DDR,and I can't find any solutions from litex documents.
> 
> Are you two in a team? Am I right to guess that it's for participating in a domestic competition? 138k with Litex isn't very practical; I suggest using SDRAM

We are not in a team.I want to boot Linux on the board,so SDRAM maybe not enough.What did you do to fix the problem?Did you do something to the source code of litedram?

**Comment by Jurisu25** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?
> > > > 
> > > > 
> > > > Sorry, it's been too long. Which repo is this issue from?
> > > 
> > > 
> > > It's from [enjoy-digital/litex#1793](https://github.com/enjoy-digital/litex/issues/1793) ,and I also meet this problem.There seems to be a problem with DDR,and I can't find any solutions from litex documents.
> > 
> > 
> > Are you two in a team? Am I right to guess that it's for participating in a domestic competition? 138k with Litex isn't very practical; I suggest using SDRAM
> 
> We are not in a team.I want to boot Linux on the board,so SDRAM maybe not enough.What did you do to fix the problem?Did you do something to the source code of litedram?

I know you want to boot Linux, and external SDRAM as memory is possible. My solution is to use external SDRAM to boot the operating system

**Comment by Stars-Collector** [comment]
> > > > > > ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?
> > > > > 
> > > > > 
> > > > > Sorry, it's been too long. Which repo is this issue from?
> > > > 
> > > > 
> > > > It's from [enjoy-digital/litex#1793](https://github.com/enjoy-digital/litex/issues/1793) ,and I also meet this problem.There seems to be a problem with DDR,and I can't find any solutions from litex documents.
> > > 
> > > 
> > > Are you two in a team? Am I right to guess that it's for participating in a domestic competition? 138k with Litex isn't very practical; I suggest using SDRAM
> > 
> > 
> > We are not in a team.I want to boot Linux on the board,so SDRAM maybe not enough.What did you do to fix the problem?Did you do something to the source code of litedram?
> 
> I know you want to boot Linux, and external SDRAM as memory is possible. My solution is to use external SDRAM to boot the operating system

OK.I don't use the official extension board,so it's hard to use external SDRAM.Thanks for your answer!

**Comment by Jurisu25** [comment]
> > > > > > > ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?
> > > > > > 
> > > > > > 
> > > > > > Sorry, it's been too long. Which repo is this issue from?
> > > > > 
> > > > > 
> > > > > It's from [enjoy-digital/litex#1793](https://github.com/enjoy-digital/litex/issues/1793) ,and I also meet this problem.There seems to be a problem with DDR,and I can't find any solutions from litex documents.
> > > > 
> > > > 
> > > > Are you two in a team? Am I right to guess that it's for participating in a domestic competition? 138k with Litex isn't very practical; I suggest using SDRAM
> > > 
> > > 
> > > We are not in a team.I want to boot Linux on the board,so SDRAM maybe not enough.What did you do to fix the problem?Did you do something to the source code of litedram?
> > 
> > 
> > I know you want to boot Linux, and external SDRAM as memory is possible. My solution is to use external SDRAM to boot the operating system
> 
> OK.I don't use the official extension board,so it's hard to use external SDRAM.Thanks for your answer!

Another approach is to build a SOC on Litex, use the official Gowin IP for the DDR controller, and integrate it yourself

**Comment by Stars-Collector** [comment]
> > > > > > > > ![image](https://private-user-images.githubusercontent.com/143895122/378341656-34c60c99-e51b-453f-b743-10f97047b74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDA4ODEsIm5iZiI6MTcyOTUwMDU4MSwicGF0aCI6Ii8xNDM4OTUxMjIvMzc4MzQxNjU2LTM0YzYwYzk5LWU1MWItNDUzZi1iNzQzLTEwZjk3MDQ3Yjc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmQzN2M1NDExNWIyZDUyNTM0MWI5OTcyODM3YWFkMWVmMjI3NjJkOTMzM2E3ZWZkZTcwYjlhMjY5NWNiNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KKLaawXpk-6nuVHBOb21EZbAcE1QuHJ-CzM5cw1Akxs) Could you please tell me how to solve this problem mentioned in this picture?
> > > > > > > 
> > > > > > > 
> > > > > > > Sorry, it's been too long. Which repo is this issue from?
> > > > > > 
> > > > > > 
> > > > > > It's from [enjoy-digital/litex#1793](https://github.com/enjoy-digital/litex/issues/1793) ,and I also meet this problem.There seems to be a problem with DDR,and I can't find any solutions from litex documents.
> > > > > 
> > > > > 
> > > > > Are you two in a team? Am I right to guess that it's for participating in a domestic competition? 138k with Litex isn't very practical; I suggest using SDRAM
> > > > 
> > > > 
> > > > We are not in a team.I want to boot Linux on the board,so SDRAM maybe not enough.What did you do to fix the problem?Did you do something to the source code of litedram?
> > > 
> > > 
> > > I know you want to boot Linux, and external SDRAM as memory is possible. My solution is to use external SDRAM to boot the operating system
> > 
> > 
> > OK.I don't use the official extension board,so it's hard to use external SDRAM.Thanks for your answer!
> 
> Another approach is to build a SOC on Litex, use the official Gowin IP for the DDR controller, and integrate it yourself

I'm trying to modify the source code of litedram.I will also consider your proposal.

**Comment by 2575ahxu** [comment]
Sorry to bother you again, i've tried to use sdram to boot linux as you memtioned, finding out that "data errors" still existed. Any suggestions? @kevinsu20
